from __future__ import annotations

from typing import Any


SEMANTIC_METRIC_REGISTRY: list[dict[str, Any]] = [
    {
        "metric_family": "scale_metric",
        "candidate_metric_ids": ["scale_by_object", "scale_total", "object_scale_ranking"],
        "required_role_patterns": [["object_key", "amount_field"], ["object_key", "quantity_field"]],
        "optional_role_patterns": [["time_key"], ["category_key"], ["channel_key"]],
        "forbidden_without_roles": [],
        "calculation_executor": "deterministic_groupby_sum",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
            "generic_business_report",
        ],
        "evidence_rules": {"direct": "A_DIRECT", "derived": "B_DERIVED", "proxy": "C_PROXY"},
        "downstream_usage_rules": [
            "can_support_scale_conclusion",
            "can_support_object_contribution_conclusion",
        ],
    },
    {
        "metric_family": "efficiency_metric",
        "candidate_metric_ids": ["efficiency_ratio", "cost_efficiency", "channel_efficiency"],
        "required_role_patterns": [["amount_field", "cost_field"], ["campaign_key", "spend_field", "conversion_field"]],
        "optional_role_patterns": [["channel_key"], ["time_key"]],
        "forbidden_without_roles": ["cost_field"],
        "calculation_executor": "deterministic_ratio_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
        ],
        "evidence_rules": {"derived": "B_DERIVED", "proxy": "C_PROXY"},
        "downstream_usage_rules": ["can_support_efficiency_comparison"],
    },
    {
        "metric_family": "structure_metric",
        "candidate_metric_ids": ["share_by_object", "mix_by_dimension", "segmentation_structure"],
        "required_role_patterns": [["object_key", "amount_field"], ["object_key", "quantity_field"]],
        "optional_role_patterns": [["region_key"], ["customer_type_key"], ["category_key"]],
        "forbidden_without_roles": [],
        "calculation_executor": "deterministic_share_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
            "generic_business_report",
        ],
        "evidence_rules": {"direct": "A_DIRECT", "derived": "B_DERIVED"},
        "downstream_usage_rules": ["can_support_structure_conclusion"],
    },
    {
        "metric_family": "trend_metric",
        "candidate_metric_ids": ["trend_change", "period_growth", "time_window_shift"],
        "required_role_patterns": [["object_key", "time_key", "numeric_measure"]],
        "optional_role_patterns": [["amount_field"], ["quantity_field"], ["active_user_field"]],
        "forbidden_without_roles": ["time_key"],
        "calculation_executor": "deterministic_time_series_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
            "generic_business_report",
        ],
        "evidence_rules": {"derived": "B_DERIVED", "proxy": "C_PROXY", "diagnostic": "D_DIAGNOSTIC"},
        "downstream_usage_rules": ["can_support_trend_conclusion_if_time_valid"],
    },
    {
        "metric_family": "concentration_metric",
        "candidate_metric_ids": ["top_share", "long_tail_ratio", "abc_classification", "concentration_risk"],
        "required_role_patterns": [["object_key", "amount_field"], ["object_key", "quantity_field"]],
        "optional_role_patterns": [["cost_field"], ["category_key"], ["supplier_key"]],
        "forbidden_without_roles": [],
        "calculation_executor": "deterministic_concentration_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "generic_long_business_report",
            "generic_business_report",
        ],
        "evidence_rules": {"direct": "A_DIRECT", "derived": "B_DERIVED"},
        "downstream_usage_rules": ["can_support_concentration_conclusion"],
    },
    {
        "metric_family": "conversion_metric",
        "candidate_metric_ids": ["conversion_rate", "funnel_step_ratio", "path_completion"],
        "required_role_patterns": [["event_field", "user_key"], ["impression_field", "click_field"], ["click_field", "conversion_field"]],
        "optional_role_patterns": [["session_key"], ["step_key"], ["time_key"]],
        "forbidden_without_roles": [],
        "calculation_executor": "deterministic_funnel_executor",
        "allowed_domains": [
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
        ],
        "evidence_rules": {"derived": "B_DERIVED", "proxy": "C_PROXY", "diagnostic": "D_DIAGNOSTIC"},
        "downstream_usage_rules": ["can_support_funnel_conclusion_if_step_order_valid"],
    },
    {
        "metric_family": "retention_metric",
        "candidate_metric_ids": ["active_users", "cohort_retention", "returning_behavior"],
        "required_role_patterns": [["user_key", "time_key"]],
        "optional_role_patterns": [["channel_key"], ["event_field"]],
        "forbidden_without_roles": ["user_key", "time_key"],
        "calculation_executor": "deterministic_retention_executor",
        "allowed_domains": ["internet_operations_report", "generic_long_business_report"],
        "evidence_rules": {"derived": "B_DERIVED", "proxy": "C_PROXY", "diagnostic": "D_DIAGNOSTIC"},
        "downstream_usage_rules": ["can_support_retention_conclusion_if_window_sufficient"],
    },
    {
        "metric_family": "profitability_metric",
        "candidate_metric_ids": ["gross_profit", "gross_margin", "unit_margin", "profitability_mix"],
        "required_role_patterns": [["amount_field", "cost_field"], ["price_field", "purchase_price_field"]],
        "optional_role_patterns": [["object_key"], ["time_key"]],
        "forbidden_without_roles": ["cost_field"],
        "calculation_executor": "deterministic_profit_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "generic_long_business_report",
            "generic_business_report",
        ],
        "evidence_rules": {"derived": "B_DERIVED", "unavailable": "E_UNSUPPORTED"},
        "downstream_usage_rules": ["can_support_profitability_conclusion_only_with_cost"],
    },
    {
        "metric_family": "inventory_metric",
        "candidate_metric_ids": ["inventory_turnover_proxy", "sell_through_proxy", "days_of_inventory_proxy", "inventory_risk"],
        "required_role_patterns": [["inventory_field", "quantity_field"], ["inventory_field", "amount_field", "time_key"]],
        "optional_role_patterns": [["object_key"], ["status_field"]],
        "forbidden_without_roles": ["inventory_field"],
        "calculation_executor": "deterministic_inventory_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "generic_long_business_report",
        ],
        "evidence_rules": {"derived": "B_DERIVED", "proxy": "C_PROXY", "unavailable": "E_UNSUPPORTED"},
        "downstream_usage_rules": ["inventory_strong_actions_require_inventory"],
    },
    {
        "metric_family": "risk_metric",
        "candidate_metric_ids": ["risk_scan", "complaint_risk", "supplier_risk", "inventory_risk"],
        "required_role_patterns": [["status_field"], ["text_feedback_field"], ["supplier_key", "status_field"]],
        "optional_role_patterns": [["rating_field"], ["inventory_field"], ["time_key"]],
        "forbidden_without_roles": [],
        "calculation_executor": "deterministic_risk_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
            "generic_business_report",
        ],
        "evidence_rules": {"proxy": "C_PROXY", "diagnostic": "D_DIAGNOSTIC", "derived": "B_DERIVED"},
        "downstream_usage_rules": ["risk_conclusion_requires_matching_evidence_level"],
    },
    {
        "metric_family": "quality_metric",
        "candidate_metric_ids": ["rating_level", "review_risk", "complaint_keyword_diagnostic"],
        "required_role_patterns": [["rating_field"], ["text_feedback_field"]],
        "optional_role_patterns": [["review_score_field"], ["object_key"]],
        "forbidden_without_roles": [],
        "calculation_executor": "deterministic_quality_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "generic_long_business_report",
        ],
        "evidence_rules": {"direct": "A_DIRECT", "proxy": "C_PROXY", "diagnostic": "D_DIAGNOSTIC"},
        "downstream_usage_rules": ["quality_conclusion_requires_rating_or_valid_text_evidence"],
    },
    {
        "metric_family": "benchmark_metric",
        "candidate_metric_ids": ["external_benchmark", "internal_benchmark", "comparability_check"],
        "required_role_patterns": [["benchmark_field"], ["external_reference_field"]],
        "optional_role_patterns": [["time_key"], ["object_key"]],
        "forbidden_without_roles": [],
        "calculation_executor": "deterministic_benchmark_executor",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
            "independent_industry_research_chain",
        ],
        "evidence_rules": {"proxy": "C_PROXY", "diagnostic": "D_DIAGNOSTIC", "unavailable": "E_UNSUPPORTED"},
        "downstream_usage_rules": ["benchmark_requires_comparability_limits"],
    },
    {
        "metric_family": "diagnostic_metric",
        "candidate_metric_ids": ["data_gap_question", "validation_question", "next_best_probe"],
        "required_role_patterns": [["object_key"], ["time_key"], ["text_feedback_field"]],
        "optional_role_patterns": [["amount_field"], ["quantity_field"], ["status_field"]],
        "forbidden_without_roles": [],
        "calculation_executor": "none",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
            "generic_business_report",
            "independent_industry_research_chain",
        ],
        "evidence_rules": {"diagnostic": "D_DIAGNOSTIC"},
        "downstream_usage_rules": ["diagnostic_only_not_formal_numeric_evidence"],
    },
    {
        "metric_family": "unavailable_metric",
        "candidate_metric_ids": ["unsupported_question", "blocked_metric"],
        "required_role_patterns": [],
        "optional_role_patterns": [],
        "forbidden_without_roles": [],
        "calculation_executor": "none",
        "allowed_domains": [
            "procurement_sales_report",
            "ecommerce_product_operations_report",
            "internet_operations_report",
            "media_campaign_report",
            "generic_long_business_report",
            "generic_business_report",
            "independent_industry_research_chain",
        ],
        "evidence_rules": {"unavailable": "E_UNSUPPORTED"},
        "downstream_usage_rules": ["must_not_enter_formal_management_conclusion"],
    },
]


KNOWN_ROLE_NAMES: set[str] = {
    "object_key",
    "user_key",
    "order_key",
    "product_key",
    "sku_key",
    "category_key",
    "supplier_key",
    "seller_key",
    "region_key",
    "channel_key",
    "campaign_key",
    "content_key",
    "session_key",
    "customer_type_key",
    "time_key",
    "amount_field",
    "quantity_field",
    "cost_field",
    "price_field",
    "purchase_price_field",
    "inventory_field",
    "rating_field",
    "review_score_field",
    "text_feedback_field",
    "impression_field",
    "click_field",
    "conversion_field",
    "event_field",
    "status_field",
    "benchmark_field",
    "external_reference_field",
    "step_key",
    "numeric_measure",
}


def get_metric_registry() -> list[dict[str, Any]]:
    return list(SEMANTIC_METRIC_REGISTRY)


def known_role_names() -> set[str]:
    return set(KNOWN_ROLE_NAMES)
